[config]
model = "o3-mini"
fallback_models = ["gpt-4o"]

[openai]
api_type = "azure"
api_version = "2025-01-01-preview"
api_base = "https://advogram-gpt.openai.azure.com"
deployment_id = "gpt-4o"

[pr_reviewer]
enable_review_labels_effort = true

[pr_code_suggestions]
summarize=true
